# Generated by Django 5.1.2 on 2024-10-19 17:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_customuser_is_trusted'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_api_call',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last api call'),
        ),
    ]
