# Generated by Django 5.1.2 on 2024-10-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_account_last_api_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_api_call',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
