# Generated by Django 5.1.2 on 2024-10-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_remove_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='true_prob',
        ),
    ]
