# Generated by Django 5.1.2 on 2024-10-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_remove_post_true_prob'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('P', 'Processing..'), ('V', 'Verified'), ('DP', 'Disproven'), ('DF', 'Definitely False'), ('PF', 'Probably False'), ('NS', 'Not Sure'), ('PT', 'Probably True'), ('DT', 'Definitely True')], default='Processing..', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='true_prob',
            field=models.FloatField(default=-1, verbose_name='Prop'),
        ),
    ]
