# Generated by Django 5.1.2 on 2024-10-23 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_following'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Post'},
        ),
    ]
